language: python

python:
    - 2.7
    - pypy
    - 3.4
    - 3.5
    - 3.6
    - 3.7
    - 3.8
env:
    - TOXENV=py,codecov

matrix:
    include:
        - python: 3.6
          env: TOXENV=py-babelex,codecov
        - python: 3.6
          env: TOXENV=py-no-babel,codecov
        - python: 3.8
          env: TOXENV=docs-html

install:
    - pip install tox

script:
    - tox

cache:
    - pip

notifications:
    email: false
